export const SET_USER = 'SET_USER';
export const SET_EMAIL = 'SET_EMAIL';
export const SET_EMAIL_ERROR = 'SET_EMAIL_ERROR';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_PASSWORD_ERROR = 'SET_PASSWORD_ERROR';
export const SET_HAS_ACCOUNT = 'SET_HAS_ACCOUNT';

export const SET_PRODUCT_NAME = 'SET_PRODUCT_NAME';
export const SET_PRODUCT_NAME_ERROR = 'SET_PRODUCT_NAME_ERROR';
export const SET_PRODUCT_DESCRIPTION = 'SET_PRODUCT_DESCRIPTION';
export const SET_PRODUCT_DESCRIPTION_ERROR = 'SET_PRODUCT_DESCRIPTION_ERROR';
export const SET_PRODUCT_IMAGE = 'SET_PRODUCT_IMAGE';
export const SET_PRODUCT_IMAGE_ERROR = 'SET_PRODUCT_IMAGE_ERROR';
export const SET_PRODUCT_PRICE = 'SET_PRODUCT_PRICE';
export const SET_PRODUCT_PRICE_ERROR = 'SET_PRODUCT_PRICE_ERROR';
export const SET_PRODUCT_DISCOUNT_PRICE = 'SET_PRODUCT_DISCOUNT_PRICE';

export const SET_BD_PRODUCTS = 'SET_BD_PRODUCTS';
